Samsung/TICO

infra/scripts/test_run.py
test/pt2_to_qcircle_test/builder.py
test/quantization/algorithm/test_gptq.py
test/quantization/algorithm/test_smooth_quant.py
test/unit_test/quantization_test/test_evaluate.py

This commit introduces --include-internal option.
Related: #12 

Introduce include-internal option in ccex test

---

test/quantization/pass/test_insert_quantize_on_dtype_mismatch.py
tico/experimental/quantization/passes/insert_quantize_on_dtype_mismatch.py
tico/utils/convert.py

This inserts Quantize Op into the place where dtype of input and node mismatch.
---
Related to: Support crispy-quantized Llama 3.2

Insert Quantize Op On Dtype Mismatch

---

test/quantization/pass/test_propagate_quant_param.py
tico/experimental/quantization/passes/propagate_qparam_forward.py
tico/utils/convert.py

This renames PropagateQuantParam to PropagateQParamForward.

Rename PropagateQuantParam to PropagateQParamForward

---

test/quantization/pass/test_propagate_qparam_backward.py
tico/experimental/quantization/passes/propagate_qparam_backward.py

This propagates qparam of permute Op backward.

Propagate qparam backward for permute Op

---

test/quantization/pass/test_convert_layout_op_to_reshape.py
test/quantization/pass/test_insert_quantize_on_dtype_mismatch.py
test/quantization/pass/test_propagate_qparam_backward.py
test/quantization/pass/test_propagate_quant_param.py
test/unit_test/pass_test/test_fuse_redundant_reshape_to_mean.py
test/unit_test/pass_test/test_remove_redundant_reshape.py
tico/passes/convert_layout_op_to_reshape.py
tico/passes/ops.py
tico/utils/convert.py

This converts layout Op to Reshape Op.
- Squeeze and Unsuqeeze are additionally converted.
---
Related to: https://github.com/Samsung/TICO/issues/21

Convert layout Op to Reshape Op

---

test/unit_test/pass_test/test_remove_redundant_reshape.py
tico/passes/remove_redundant_reshape.py

This adds a new pattern for redundant reshape Ops.
---
Related to: https://github.com/Samsung/TICO/issues/21

Remove redundant reshape Ops

---

tico/utils/convert.py

This preserves linear Op during decomposition.

Preserve linear during decomposition

---

tico/experimental/quantization/passes/insert_quantize_on_dtype_mismatch.py
tico/serialize/operators/op_quantize_per_tensor.py
tico/utils/utils.py

This includes the following changes.
- quant_min and quant_max are properly set.
- use circle tensor's qparam in quantize_per_tensor.

Use proper quantization parameters

---

.github/workflows/check-pr.yaml

Let's check whether contributors are following TICO DCO.
#31

[CI] Add check-commit-message job

---

.github/workflows/check-pr.yaml

Let's fix it to run.
----
:heavy_check_mark: Checked that it does not skip
:heavy_check_mark: Checked that it fails without signoff
:heavy_check_mark: Checked that it passes with signoff

[CI] Fix check-commit-message

---

.github/workflows/check-pr.yaml

This commit fixes broken link which redirects to the WIKI page about DCO from the `check-pr` workflow
TICO-DCO-1.0-Signed-off-by: Jihun-Kim <jeyjey6@naver.com>
---
related to: #40

[CI] Fix broken link in comment

---

test/quantization/pass/test_insert_quantize_on_dtype_mismatch.py
tico/experimental/quantization/passes/insert_quantize_on_dtype_mismatch.py

This adds Reshape Op to InsertQuantizeOnDtypeMismatch.

Add Reshape to InsertQuantizeOnDtypeMismatch

---

test/modules/op/index.py
test/unit_test/pass_test/test_lower_to_slice.py
tico/passes/lower_to_slice.py
tico/utils/convert.py

Let's introduce LowerIndexSelectToSlice.
It lowers index_select op to slice `selectively` when its index is constant tensor.

[passes] Introduce LowerIndexSelectToSlice

---

test/modules/op/add.py

This commit expands a rank of tensors for calibration.
Note that current backend compiler doesn't support 1-rank tensor.

[test] Fix SimpleAdd quantization test

---

test/modules/op/avg_pool2d.py

This commit temporarily turns off a quantization test.
It will be turned on after #52 is resolved.

[test] Temporarily turn off quantization test for AdaptiveAvgPool

---

.github/workflows/check-pr.yaml

This commit uses Google's docker hub mirror
---
For issue #72

[CI] Use Google's docker hub mirror

---

.github/workflows/check-pr.yaml

This commit updates ubuntu docker image repository to use azure internal cache repository.

[action] Use Azure internal cache repository

---

infra/scripts/install_requirements_2_5.txt
infra/scripts/install_requirements_2_6.txt
infra/scripts/install_requirements_dev.txt

This commit resolves a security vulnerability.

Bump setuptools from 69.2.0 to 78.1.1

---

tico/experimental/quantization/passes/remove_weight_dequant_op.py
tico/passes/decompose_fake_quantize_tensor_qparams.py

This commit considers buffers and lifted tensors to get tensors.

Consider buffers and lifted tensors

---

test/modules/op/native_group_norm.py
test/modules/op/native_layer_norm.py
tico/passes/decompose_group_norm.py
tico/serialize/operators/op_mean.py
tico/utils/validate_args_kwargs.py

This commit removes redundant reshapes when exporting GroupNorm.
Related: #97 

Remove Redundant Reshape when exporting GroupNorm

---

test/unit_test/pass_test/test_decompose_fake_quantize.py
test/unit_test/pass_test/test_decompose_fake_quantize_tensor_qparam.py
test/unit_test/utils_test/test_utils.py
tico/experimental/quantization/passes/fold_quant_ops.py
tico/experimental/quantization/passes/remove_weight_dequant_op.py
tico/passes/decompose_fake_quantize.py
tico/passes/decompose_fake_quantize_tensor_qparams.py
tico/utils/utils.py

This commit supports fake-quantized module with uint4 dtype.

Support fake-quantize with uint4 dtype

---

test/pt2_to_circle_test/builder.py
test/pt2_to_circle_test/test_pt2_to_circle.py

Let's infer before export, to avoid the model's internal state change due to 'export leakage'.
---
#129

[test] Infer before export

---

tico/passes/fuse_leading_unsqueeze_reshape.py
tico/passes/remove_redundant_reshape.py
tico/serialize/operators/op_reshape.py
tico/utils/validate_args_kwargs.py

This commit aligns reshape's argument name according to spec.

Rename aten.reshape argument name

---

test/modules/op/linear.py
test/pt2_to_circle_test/builder.py
test/utils/tag.py
tico/experimental/quantization/passes/quantize_bias.py
tico/experimental/quantization/passes/remove_weight_dequant_op.py
tico/utils/convert.py

This supports fake-quantized linear with fp32 bias.
---
Related to: #149

Support fake-quantized linear with fp32 bias

---

test/modules/op/leaky_relu.py
tico/serialize/operators/op_leaky_relu.py
tico/utils/validate_args_kwargs.py

This commit supports LeakyReLU.

[serialize] Support LeakyReLU

---

test/quantization/pass/test_fold_quant_ops.py
tico/experimental/quantization/passes/fold_quant_ops.py

This inserts Quantize Op in FoldQuantOps pass.
---
Related to: #165

[pass] Insert Quantize Op in FoldQuantOps pass

---

tico/experimental/quantization/passes/fold_quant_ops.py

This commit considers multiple DQ case in SimpleAdd.
The case happens with pt2 quantization.

[passes] Consider multiple DQ case

---

tico/passes/decompose_fake_quantize_tensor_qparams.py

This commit prints unsupported min/max values for debugging.

[passes] Print unsupported value

---

.pylintrc

This commit adds .pylintrc for pylint.
Related: #170 

Add .pylintrc

---

test/modules/op/conv2d.py
tico/serialize/operators/op_conv2d.py
tico/utils/padding.py

This commit fixes the logic when it has SAME padding.

Fix conv with SAME padding

---

test/quantization/pass/test_insert_quantize_on_dtype_mismatch.py
tico/experimental/quantization/passes/insert_quantize_on_dtype_mismatch.py

This adds Add, Relu in InsertQuantizeOpOnDtypeMismatch.
---
Related to: #165

Support Add, Relu in InsertQuantizeOpOnDtypeMismatch

---

test/modules/op/index.py
test/modules/op/index_select.py
test/unit_test/pass_test/test_decompose_fake_quantize.py
test/unit_test/pass_test/test_segment_index_select.py

This commit uses buffer instead of in-place tensors.
Related: #159
This change turns off below warnings.
```
/home/seongwoo/TICO/.venv/lib/python3.10/site-packages/torch/fx/graph.py:1801: UserWarning: Node segm_index2_1 target segm_index2 segm_index2 of  does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
warnings.warn(
ok
```

[test] Use buffer

---

.lintrunner.toml

This commit fixes typo of option name.

[lint] Fix typo

---

README.md

This commit adds some description to make one-compiler an optional. It's more like a testing thing.

Make one-compiler an optional dependency

---

test/modules/op/add.py
test/pt2_to_circle_test/builder.py
test/pt2_to_circle_test/test_pt2_to_circle.py
test/utils/tag.py

Let's add a golden test.
What is golden test? - It's a test that compares `golden outputs` with circle-inference result. It can be performed when torch graph is changed into different symantics.

[test] Add a golden test

---

test/modules/op/clamp.py
test/unit_test/pass_test/test_cast_clamp_mixed_type_args.py
tico/passes/cast_clamp_mixed_type_args.py
tico/passes/ops.py
tico/utils/convert.py

This pass ensures consistent dtypes for clamp operations by:
1. Converting min/max arguments to match output dtype when provided
2. Inserting cast operations when input dtype differs from output dtype
for https://github.com/Samsung/TICO/issues/179#issuecomment-3047972123

Cast mixed type args of clamp

---

tico/serialize/operators/op_softmax.py
tico/utils/utils.py

This commit deprecates HAS_TORCH_OVER_25.
torch under 2.5 already can't any tests. `HAS_TORCH_OVER_25` is useless.

Deprecate HAS_TORCH_OVER_25

---

test/utils/infer.py

This commit adds support kwargs to infer with onert.(like circle-interpreter)

Support kwargs to infer with onert

---

test/modules/op/interpolate.py
tico/utils/convert.py
tico/utils/utils.py

This commit adds an aten.upsample_nearest2d to preserve op list.
We don't have to check the version with this patch.

Do not decompose aten.upsample_nearest2d

---

tico/passes/decompose_addmm.py
tico/passes/decompose_fake_quantize.py
tico/passes/decompose_group_norm.py
tico/passes/legalize_predefined_layout_operators.py
tico/passes/remove_redundant_reshape.py
tico/serialize/operators/op_any.py
tico/serialize/operators/op_instance_norm.py
tico/serialize/operators/op_mul.py
tico/serialize/operators/op_transpose_conv.py

Let's remove unused variables.
For easy check, run `ruff check | grep F841`.
---
From #231

Remove unused variables

---

test/modules/op/depthwise_conv2d.py
test/unit_test/serialize_test/test_circle_graph.py
tico/serialize/circle_graph.py
tico/serialize/circle_mapping.py
tico/serialize/circle_serializer.py
tico/serialize/operators/op_any.py
tico/serialize/operators/op_avg_pool2d.py
tico/serialize/operators/op_clamp.py
tico/serialize/operators/op_conv2d.py
tico/serialize/operators/op_copy.py
tico/serialize/operators/op_cumsum.py
tico/serialize/operators/op_depthwise_conv2d.py
tico/serialize/operators/op_index_select.py
tico/serialize/operators/op_log1p.py
tico/serialize/operators/op_max_pool2d_with_indices.py
tico/serialize/operators/op_mm.py
tico/serialize/operators/op_pow.py
tico/serialize/operators/op_repeat.py
tico/serialize/operators/op_reshape.py
tico/serialize/operators/op_split_with_sizes.py
tico/serialize/operators/op_transpose_conv.py
tico/serialize/operators/op_view.py

Let's enforce teh type contract by ensuring that only int values are stored in circle tensor.shape.

Pass shape signature to circle tensor creation interface

---

test/quantization/pass/test_insert_quantize_on_dtype_mismatch.py
tico/experimental/quantization/passes/insert_quantize_on_dtype_mismatch.py

This supports i8o16 relu in InsertQuantizeOpPass.

Support i8o16 relu in InsertQuantizeOpPass

---

tico/serialize/circle_graph.py
tico/serialize/operators/op_copy.py
tico/serialize/operators/op_cumsum.py
tico/serialize/operators/op_pow.py

Let's fix type annotation of Tensor.shapeSignature. NOTE: Tensor.shapeSignature has type of Optional[List[int]]. Flatbuffers fails in type annotation, generating it as List[int].
---
Related to https://github.com/Samsung/TICO/issues/244
> Never use [] for shape_signature. Always use None for static shapes.
> If you get typing errors from this, just add a # type: ignore comment to suppress mypy warnings.

[serialize] Fix type annotation

---

test/unit_test/serialize_test/test_circle_mapping.py
test/unit_test/utils_test/test_serialize.py
tico/serialize/circle_mapping.py
tico/serialize/circle_serializer.py
tico/utils/serialize.py

Let's validate circle tensor's shape and shape signature values.
TICO-DCO-1.0-Signed-off-by: Dayoung Lee [dayoung.lee@samsung.com](mailto:dayoung.lee@samsung.com)
---
Related to #244

[serialize] Validate shapeSignature

---

test/quantization/algorithm/test_gptq.py

This commit runs more calib for GPTQ.
Before this PR, sometimes the test fails because the number of calibration is a bit small.

[test] Run more calib for GPTQ

---

test/modules/model/SmolVLM_text_model/model.py

Let's fix its get_example_inputs.

[test] Fix SmolVLM_text_model

---

tico/utils/register_custom_op.py
tico/utils/validate_args_kwargs.py

Let's revise CircleRMSNormArgs to match with circle serialization.

Revise CircleRMSNormArgs

---

setup.py

This commit uses 'with' for resource-allocating operations.
This'll resolve pylint `PYLINT.CONSIDER_USING_WITH` error.

Use 'with' for 'open' operation in setup.py

---

tico/passes/decompose_fake_quantize_tensor_qparams.py

This commit adds missing assert keyword.

[passes] Add missing assert keyword

---

tico/utils/utils.py

This commit uses a generator instead of list comprehension.
This resolves pylint error.

[utils] Use a generator

---

test/quantization/ptq/observers/test_ema.py
test/quantization/ptq/observers/test_identity.py
tico/experimental/quantization/ptq/observers/__init__.py
tico/experimental/quantization/ptq/observers/ema.py
tico/experimental/quantization/ptq/observers/identity.py

This commit adds more observers that are commonly used.
- Percentile
- EMA
- Identity
Related: https://github.com/Samsung/TICO/issues/89
Draft: https://github.com/Samsung/TICO/pull/212

[ptq] Add more observers

---

test/quantization/ptq/observers/test_mx.py
tico/experimental/quantization/ptq/observers/__init__.py
tico/experimental/quantization/ptq/observers/mx.py

This commit introduces MXObserver for MX quantization.
Related: https://github.com/Samsung/TICO/issues/89
Draft: https://github.com/Samsung/TICO/pull/212

[ptq] Introduce MXObserver

---

test/quantization/ptq/wrappers/test_ptq_wrapper.py
tico/experimental/quantization/ptq/wrappers/ptq_wrapper.py

This commit introduces a wrapping helper class.
Without this class, users should import quant wrapper class for each torch modules.
Related: https://github.com/Samsung/TICO/issues/89
Draft: https://github.com/Samsung/TICO/pull/212

[ptq] Introduce a wrapping helper class

---

test/quantization/ptq/wrappers/test_ptq_wrapper.py
tico/experimental/quantization/ptq/wrappers/ptq_wrapper.py

This commit fixes double interation issue of PTQ wrapper.
Before this PR, there's a double interation bug when a parent wrapper class iterates subsequent observers. Because the submodule includes not only a quant wrapper module but also its `PTQWrapper` that wraps the module.

[ptq] Fix double iteration of observer

---

test/quantization/ptq/wrappers/llama/test_quant_attn.py

This commit makes a test version-agnostic.
Some old transformers versions have different in/out spec. This commit covers them.

[ptq] Fix llama attention test

---

test/modules/model/BitNet_b1_58/requirements.txt

BitNet test fails with latest transformers(4.56), so it fixes transformers version to 4.55.4

[test] Fix requirement.txt for BitNet test

---

test/quantization/ptq/utils/test_introspection.py
tico/experimental/quantization/ptq/examples/debug_quant_outputs.py
tico/experimental/quantization/ptq/utils/introspection.py

This commit introduces debugigng APIs.
```bash
python tico/experimental/quantization/ptq/examples/debug_quant_outputs.py
Calibrating with 50,000 tokens.
Loading FP model …
`rope_scaling`'s original_max_position_embeddings field must be less than max_position_embeddings, got 2048 and max_position_embeddings=2048
Using the latest cached version of the dataset since wikitext couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'wikitext-2-raw-v1' at /home/sw4670.chae/.cache/huggingface/datasets/wikitext/wikitext-2-raw-v1/0.0.0/b08601e04326c79dfdd32d625aee71d232d685c3 (last modified on Fri May  3 21:06:41 2024).
Wrapping layers with PTQWrapper …
Calibrating UINT-8 observers …
Act-calibration: 100%|██████████████████████████████████████████████████████████████ …
```

[ptq] Introduce Debugging APIs

---

tico/experimental/quantization/ptq/wrappers/llama/quant_attn.py
tico/experimental/quantization/ptq/wrappers/registry.py

This commit supports multiple registration.
This fixes an error that happened when old `transformers` use `LlamaSdpaAttention` instead of `LlamaAttention` which is used latest `transformers`.

[ptq] Support multiple registration

---

infra/style/format.sh

This adds aliasing -d for --diff-only.

Support ccex format -d

---

test/unit_test/utils_test/test_signature.py
tico/utils/signature.py

This commit checks the number of passed args when binding.
Related: https://github.com/Samsung/TICO/pull/347#issuecomment-3300913765

[utils] Check the number of passed args

---

tico/experimental/quantization/ptq/examples/compare_ppl.py
tico/experimental/quantization/ptq/examples/debug_quant_outputs.py

This commit removes redundant help messages.

[ptq] Remove redundant help messages

---

test/modules/op/constant_pad_nd.py
tico/serialize/operators/op_constant_pad_nd.py

This commit adds support to 2/6/8 length of pads

[serialize] Support more padding length

---

test/quantization/ptq/wrappers/fairseq/test_decoder_export_single_step.py
tico/experimental/quantization/ptq/wrappers/fairseq/decoder_export_single_step.py

This commit introduces a wrapper for decoder export.
This class is necessary for the decoder export that will be compiled with compilers of accelerators.

[ptq] Introduce a wrapper for decoder export

---

.github/workflows/check-pr.yaml

To fix CI failure, this commit upgrades ONE version to 1.30.1
---
Related https://github.com/Samsung/ONE/issues/16110

[CI] Upgrade ONE version to 1.30.1

---

tico/passes/ops.py

This commit fixes AtenOps view
- is_target_node assuems every nodes are instance of OpOverload
- torch.ops.aten.view is not a instance of OpOverload

[passes] Fix AtenOps view
