- README.md
This commit updates the README to reflect the requirement.
Related: #2 
> Update README to specify ONE Compiler nightly requirement

- .github/actionlint.yaml
- .github/workflows/check-pr.yaml
This commit uses hosted runner.
> [action] Use hosted runner

- tico/experimental/quantization/passes/remove_weight_dequant_op.py
This supports more constant scales and zeop other than named_buffers.
---
Related to: Support crispy-quantized Llama 3.2
> Support more constant scales and zerop

- test/unit_test/serialize_test/test_pack.py
- tico/experimental/quantization/passes/remove_weight_dequant_op.py
- tico/serialize/circle_graph.py
- tico/serialize/circle_mapping.py
- tico/serialize/pack.py
This supports export of uint4 weights.
---
https://github.com/Samsung/TICO/issues/15
> Support uint4 weights

- tico/utils/convert.py
This revises quantization steps
- Do quantization after optimization
- Remove FillMetaQuantVal
---
Related to: Support crispy-quantized Llama 3.2
> Revise quantization steps

- infra/style/format.sh
This adds --diff-only option to ./ccex format.
---
Related to: https://github.com/Samsung/TICO/issues/46
> Format only diff from main

- tico/passes/lower_to_resize_nearest_neighbor.py
- tico/utils/validate_args_kwargs.py
> [trivial] Revise comments

- .github/workflows/publish-nightly-package.yaml
- setup.py
Let's publish nightly-release packages to pypi.
> [CI] Publish to pypi nightly

- LICENSE
> [LICENSE] Fix typo

- test/modules/model/EfficientNetV2S/requirements.txt
- test/modules/model/InceptionV3/requirements.txt
- test/modules/model/MobileNetV2/requirements.txt
- test/modules/model/MobileNetV3S/requirements.txt
- test/modules/model/ResNet18/requirements.txt
This commit removes nightly dependencies.
We won't have to worry about the version updates as much if we change it like this.
> [test] Remove nightly dependency

- .github/workflows/check-pr.yaml
This commit removes duplicated python installs
---
Resolve #59 
From draft #60
> [CI] Remove duplicated python installs

- README.md
- infra/scripts/test_run.py
- test/pt2_to_circle_test/builder.py
- test/pt2_to_circle_test/test_pt2_to_circle.py
- test/utils/base_builders.py
- test/utils/helper.py
- test/utils/infer.py
- test/utils/runtime.py
- test/utils/tag.py
This commit supports ONERT backend.
Related: #64 
> [test] Support ONERT backend

- .github/workflows/check-pr.yaml
This commit prepares format/style check only in check-style job
---
For issue #74
> [CI] Prepare format/style check only in check-style job

- infra/scripts/install.sh
- infra/scripts/install_requirements_2_5.txt
- infra/scripts/install_requirements_2_6.txt
- infra/scripts/install_requirements_dev.txt
This commit adds --no-deps for dist install
---
To resolve #69 
For issue #74
> [ccex] Add --no-deps for dist install

- README.md
This commit helps how to install nighlty version of ONERT.
> Add ONERT installation section

- test/modules/op/linear.py
- test/pt2_to_circle_test/builder.py
- test/pt2_to_circle_test/test_pt2_to_circle.py
This commit introduces tests with dynamic shapes.
Related: #48
> [test] Introduce tests with dynamic shapes

- infra/dependency/torch_dev.txt
- infra/dependency/torchvision_dev.txt
- Updated requirements.txt
- Verified compatatibility with existing tests.
> [infra] Upgrade PyTorch to latest nightly version

- test/requirements_2_5.txt
- test/requirements_2_6.txt
This commit installs CPU version for torchvision.
torch and torchvision should be aligned.
> [test] Install CPU version for torchvision

- infra/dependency/torch_dev.txt
- infra/dependency/torchvision_dev.txt
- infra/scripts/install.sh
- infra/scripts/install_requirements_2_5.txt
- infra/scripts/install_requirements_2_6.txt
- infra/scripts/install_requirements_dev.txt
- infra/scripts/test_configure.sh
- test/requirements_2_5.txt
- test/requirements_2_6.txt
This commit supports CUDA-aware torch installation.
Related: #92 
> [infra] Support CUDA-aware torch installation

- infra/scripts/install.sh
- infra/scripts/install_requirements_2_7.txt
- infra/scripts/test_configure.sh
This commit imporve ./ccex install/configure version handling.
Change details are in the related issue.
I recommend that you just review entire files with "View file" tab because the changes are a bit huge.
Related: #94 
> [infra] Improve ./ccex Torch version handling

- tico/utils/utils.py
This commit fixes typo.
Related: https://github.com/Samsung/TICO/pull/112#discussion_r2110947718
> [utils] Fix typo

- test/modules/op/abs.py
- test/pt2_to_circle_test/test_pt2_to_circle.py
- tico/serialize/circle_serializer.py
Let's ignore None output from graph signature.
> [serialize] Ignore None output

- tico/passes/remove_redundant_reshape.py
> [passes] Use Args class

- tico/passes/cast_aten_where_arg_type.py
- tico/passes/cast_mixed_type_args.py
- tico/passes/convert_conv1d_to_conv2d.py
- tico/passes/convert_repeat_to_expand_copy.py
- tico/passes/decompose_addmm.py
- tico/passes/decompose_batch_norm.py
- tico/passes/decompose_fake_quantize.py
- tico/passes/decompose_fake_quantize_tensor_qparams.py
- tico/passes/decompose_group_norm.py
- tico/passes/decompose_grouped_conv2d.py
- tico/passes/decompose_slice_scatter.py
- tico/passes/extract_dtype_kwargs.py
- tico/passes/fuse_leading_unsqueeze_reshape.py
- tico/passes/fuse_redundant_reshape_to_mean.py
- tico/passes/legalize_causal_mask_value.py
- tico/passes/legalize_predefined_layout_operators.py
- tico/passes/lower_pow2_to_mul.py
- tico/passes/lower_to_resize_nearest_neighbor.py
- tico/passes/lower_to_slice.py
- tico/passes/merge_consecutive_cat.py
- tico/passes/remove_nop.py
- tico/passes/remove_redundant_assert_nodes.py
- tico/passes/remove_redundant_expand.py
- tico/passes/remove_redundant_permute.py
- tico/passes/remove_redundant_reshape.py
- tico/passes/remove_redundant_slice.py
- tico/passes/remove_redundant_to_copy.py
- tico/passes/segment_index_select.py
- tico/serialize/operators/op_where.py
- tico/utils/utils.py
This commit reduces duplicate codes that checks target nodes.
> Reduce duplicate codes

- .github/workflows/publish-official-package.yaml
This commit adds a workflow that publishes official pakcage.
> [action] Add a workflow for publishing official package

- .github/workflows/check-pr.yaml
This commit adds torch 2.7 test.
> [action] Add torch 2.7 test

- test/pt2_to_circle_test/builder.py
During `forward` or `export`, example_inputs could change. To prevent it, let's use the copy of them.
---
From #173
> [test] Use copy of example_inputs for immutablity

- .github/actions/download-release-asset/action.yml
- .github/workflows/check-pr.yaml
This commit uses one-compiler 1.30.0.
Related: #2 
> [action] Use one-compiler 1.30.0

- test/modules/op/round.py
- tico/serialize/operators/op_round.py
- tico/utils/validate_args_kwargs.py
This commit support round op.
ONE-DCO-1.0-Signed-off-by: Seockho Kim seockho.kim@samsung.com
for https://github.com/Samsung/TICO/issues/179
> Support round op

- tico/utils/model.py
This commit adds a Path type hint.
> Add Path type hint

- tico/experimental/quantization/passes/insert_quantize_on_dtype_mismatch.py
This refactors InsertQuantizeOpOnDtypeMismatch.
> Refactor InsertQuantizeOpOnDtypeMismatch

- test/modules/op/index_select.py
- test/pt2_to_circle_test/test_pt2_to_circle.py
- test/unit_test/pass_test/test_decompose_fake_quantize.py
- test/unit_test/pass_test/test_segment_index_select.py
Let's enhance type checking.
---
For #236
> Add type check asserts

- test/modules/op/avg_pool2d.py
- test/modules/op/conv2d.py
- test/modules/op/conv_transpose2d.py
- test/modules/op/depthwise_conv2d.py
- test/modules/op/max_pool2d.py
- test/modules/op/repeat.py
- tico/serialize/circle_graph.py
- tico/serialize/circle_mapping.py
- tico/serialize/operators/op_avg_pool2d.py
- tico/serialize/operators/op_conv2d.py
- tico/serialize/operators/op_depthwise_conv2d.py
- tico/serialize/operators/op_max_pool2d_with_indices.py
- tico/serialize/operators/op_repeat.py
- tico/serialize/operators/op_transpose_conv.py
- tico/utils/padding.py
- tico/utils/serialize.py
Let's utilize torch.SymInt for shape check.
Operation Coverage:
- Average Pooling (avg pool)
- Convolution (conv)
- Depthwise Convolution (depthwise conv)
- Transpose Convolution (transpose conv)
- Max Pool (max pool)
- Repeat
---
For #233
> Enable Dynamic Shapes with Padding Consideration

- test/quantization/algorithm/test_gptq.py
- tico/experimental/quantization/algorithm/gptq/quantizer.py
- tico/experimental/quantization/algorithm/gptq/utils.py
- tico/experimental/quantization/public_interface.py
This commit revises GPTQ to make it support multiple inputs.
> [quantization] Revise GPTQ quantizer

- test/pt2_to_circle_test/builder.py
It's missing to set dynamic_shape.
> [test] Fix builder

- tico/experimental/quantization/algorithm/pt2e/README.md
This fixes url in the pt2e README.md.
> Fix urls in pt2e README.md

- test/modules/op/add.py
- test/modules/op/avg_pool2d.py
- test/modules/op/conv2d.py
- test/pt2_to_qcircle_test/builder.py
Let them return generator to save from further possible memory problem.
> [test] Revise get_calibration_data

- test/unit_test/quantization_test/test_metric.py
- tico/experimental/quantization/evaluation/metric.py
> [quantization] Add MSE metric

- test/quantization/algorithm/test_gptq.py
This commit fixes a bug in GPTQ test.
> [quantization] Fix GPTQ test

- test/pt2_to_circle_test/builder.py
Let's check if dynamic shape is applied to input signatures as expected.
> [test] Check dynamic shape signature

- tico/utils/utils.py
This commit resolves pylint error.
- Move function definitions outside the loop.
- Use generator instead of list comprehension.
> [utils] Resolve pylint error

- test/quantization/ptq/wrappers/test_quant_module_base.py
- tico/experimental/quantization/ptq/observers/ema.py
- tico/experimental/quantization/ptq/observers/identity.py
- tico/experimental/quantization/ptq/quant_config.py
- tico/experimental/quantization/ptq/wrappers/quant_module_base.py
This commit cleans up and format docstrings.
> [ptq] Clean up and format docstrings

- test/quantization/ptq/wrappers/test_quant_elementwise.py
- tico/experimental/quantization/ptq/wrappers/quant_elementwise.py
This commit introduces a wrapper class for elementwise modules.
Related: https://github.com/Samsung/TICO/issues/89
Draft: https://github.com/Samsung/TICO/pull/212
> [ptq] Introduce Quant elementwise wrapper class

- test/quantization/ptq/wrappers/test_quant_module_base.py
- tico/experimental/quantization/ptq/wrappers/quant_module_base.py
This commit finds child quant modules inside nn containers.
Decoder often has its layers as a `nn.ModuleList`.
> [ptq] Find child quant modules inside nn container

- infra/dependency/torch_dev.txt
- infra/dependency/torchvision_dev.txt
This commit bumps up torch nightly version.
> [infra] Bump up nightly version

- tico/experimental/quantization/ptq/examples/quantize_llama_mlp.py
This commit uses practical prompts.
Related: https://github.com/Samsung/TICO/pull/295#discussion_r2302894941
> [ptq] Use practical prompts

- test/pt2_to_qcircle_test/builder.py
- test/quantization/algorithm/test_gptq.py
- test/quantization/algorithm/test_smooth_quant.py
- test/quantization/ptq/utils/test_introspection.py
- test/unit_test/quantization_test/test_evaluate.py
This commit renames a variable for internal test.
Related: https://github.com/Samsung/TICO/pull/307#discussion_r2315309113
> Rename a variable for internal test

- test/quantization/algorithm/test_smooth_quant.py
- tico/experimental/quantization/algorithm/smoothquant/observer.py
- tico/experimental/quantization/algorithm/smoothquant/quantizer.py
- tico/experimental/quantization/algorithm/smoothquant/smooth_quant.py
- tico/experimental/quantization/config.py
This commit supports output hook option and add fairseq logic as an example.
> [quantization] Support output hook

- test/quantization/algorithm/test_smooth_quant.py
This commit removes unused variables.
> [test] Remove unused variables

- test/quantization/ptq/wrappers/fairseq/test_quant_encoder_layer.py
- tico/experimental/quantization/ptq/wrappers/fairseq/quant_encoder_layer.py
- tico/experimental/quantization/ptq/wrappers/registry.py
This commit introduces a wrapper for fairseq encoder layer.
> [ptq] Introduce fairseq encoder layer wrapper

- test/unit_test/quantization_test/test_adaptive_avg_pool2d.py
This adds tests for annotating adaptive_avgpool_2d.
---
Related to: https://github.com/Samsung/TICO/issues/322
> [test] Add tests for annotating adaptive_avgpool_2d

- tico/experimental/quantization/ptq/examples/debug_quant_outputs.py
This commit makes a script configurable.
This is necessary for integrating example scripts into the CI.
```bash
python tico/experimental/quantization/ptq/examples/debug_quant_outputs.py --model Maykeye/TinyLLama-v0
=== Config ===
Model            : Maykeye/TinyLLama-v0
Device           : cuda
DType            : float32
Stride           : 512
Calib preset     : debug (2,000 tokens)
Use HF cache?    : False
Loading FP model …
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and …
```
> [ptq] Make debug_quant_outputs script configurable

- tico/experimental/quantization/ptq/examples/quantize_with_gptq.py
This commit makes a script configurable.
This is necessary for integrating example scripts into the CI.
```
python tico/experimental/quantization/ptq/examples/quantize_with_gptq.py --model Maykeye/TinyLLama-v0
=== Config ===
Model            : Maykeye/TinyLLama-v0
Device           : cuda
DType            : float32
Stride           : 512
Calib preset     : debug (2,000 tokens)
Use HF cache?    : False
Loading FP model …
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly …
```
> [ptq] Make quantize_with_gptq script configurable

- test/modules/model/Florence2/model.py
This commit fixes Florence2 model test failure.
Recently, the max difference grows a little bit, so we need to update atol/rtol.
> [test] Fix Florence2 model test failure
